### PR TITLE
#82 Determine docker-compose location dynamically

### LINKED ISSUE #82: Docker Compose under a different location is not recognized
I see that docker-compose is required for installing: [line in file](https://github.com/rafalp/misago_docker/blob/master/appctl#L19). This assumes that the docker compose binary is located at `/usr/local/bin/docker-compose`. I installed docker-compose using the [instructions provided by DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-ubuntu-16-04), and this put the docker-compose binary in `/usr/bin/docker-compose`.

```bash
misago@ubuntu-dataswamp-forum:~/misago_docker$ which docker-compose
/usr/bin/docker-compose
```

Would it be possible to use `$(which docker-compose)` to find where docker compose is?

ALso, let me say that the infrastructure and documentation you have for this project is _so awesome_! I can't tell y'all how much I appreciate it :smile: I spent 10 hours trying to set up a different solution that had some really outdated documentation - I'm glad you've made this so easy.

### PR DESCRIPTION
**Pull request by AetherUnbound**
Resolves #82 

Let me know if there's anything else I can add! I tested this on my machine and it looks like it works.

### CODE REVIEW

**Comment by rafalp** [comment]
Thanks for this PR. Can you confirm that after this change cron still periodically runs management commands using docker compose?

https://github.com/rafalp/misago_docker/blob/master/appctl#L159

**Comment by AetherUnbound** [comment]
This is the `crontab -l` printout:

```
misago@ubuntu-dataswamp-forum:~$ crontab -l
30 1 * * * cd /home/misago/misago_docker && /usr/bin/docker-compose run --rm misago ./cron
0 1 * * * cd /home/misago/misago_docker && ./appctl daily_backup
0 1 * * * find /home/misago/misago_docker/backups/ -name auto-* -type f -mtime +10 -delete
```

However, I don't see a backup yet in `/home/misago/misago_docker/backups`. Where can I check the output of any of these cron jobs?

**Comment by AetherUnbound** [comment]
It may be because my system is in UTC:
```
misago@ubuntu-dataswamp-forum:~$ date
Tue Aug  6 15:07:31 UTC 2019
```
And the backup job simply has not run yet. I may need to adjust those crontab times.

**Comment by rafalp** [comment]
AFAIR `which docker-compose` returns nothing when script is executed by crontab, which is why I've moved it to absolute path.

**Comment by AetherUnbound** [comment]
Ah, that would definitely be problematic...Give me 24 hours to see how the scheduled cron jobs run! :P

**Comment by AetherUnbound** [comment]
The backup did indeed run!
```
misago@ubuntu-dataswamp-forum:~/misago_docker$ ll backups/
total 5076
drwxrwxr-x 2 misago misago    4096 Aug  7 08:00 ./
drwxrwxr-x 9 misago misago    4096 Aug  6 02:18 ../
-rw-rw-r-- 1 misago misago      13 Aug  6 01:45 .gitignore
-rw-rw-r-- 1 misago misago 5184006 Aug  7 08:00 auto-20190807080005.tar.gz
misago@ubuntu-dataswamp-forum:~/misago_docker$ date
Wed Aug  7 14:56:43 UTC 2019
```

It also looks like crontab ran with the appropriate docker-compose location:
```
$ sudo grep CRON /var/log/syslog
Aug  7 07:17:01 ubuntu-dataswamp-forum CRON[3184]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug  7 08:00:01 ubuntu-dataswamp-forum CRON[4617]: (misago) CMD (cd /home/misago/misago_docker && ./appctl daily_backup)
Aug  7 08:00:01 ubuntu-dataswamp-forum CRON[4618]: (misago) CMD (find /home/misago/misago_docker/backups/ -name auto-* -type f -mtime +10 -delete)
Aug  7 08:00:05 ubuntu-dataswamp-forum CRON[4616]: (CRON) info (No MTA installed, discarding output)
Aug  7 08:17:01 ubuntu-dataswamp-forum CRON[5167]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug  7 08:30:01 ubuntu-dataswamp-forum CRON[5923]: (misago) CMD (cd /home/misago/misago_docker && /usr/bin/docker-compose run --rm misago ./cron)
```

I believe it's all functioning as intended!

**Comment by rafalp** [comment]
Okay, merging!

Thanks for taking time to help! 👍

**Comment by AetherUnbound** [comment]
No worries, thanks for maintaining this project!

**Pull request merged**
